# LLM CLI v2 Configuration

llm:
  provider: ${LLM_PROVIDER::openai}

# OpenAI API Configuration
openai:
  api_url: ${API_URL::https://dashscope.aliyuncs.com/compatible-mode/v1}
  api_key: ${API_KEY::sk-dedab808e1a64810833d8e0a3d7b88c8}
  model: ${API_MODEL::glm-4.7}
  max_tokens: 1000
  temperature: 0.7
  use_stream: true
  system_message: ${SYSTEM_MESSAGE}

# qwen api configuration
qwen:
  # api_url: "http://192.168.20.220:11434/v1"
  # api_key: ""
  # model: "qwen3:8b"
  api_url: ${API_URL::https://dashscope.aliyuncs.com/compatible-mode/v1}
  api_key: ${API_KEY::sk-dedab808e1a64810833d8e0a3d7b88c8}
  model: ${API_MODEL::qwen3-8b}
  max_tokens: 1000
  temperature: 0.7
  use_stream: true
  enable_thinking: true
  thinking_budget: 4000
  system_message: ${SYSTEM_MESSAGE}



# Tool Calling Configuration
tools:
  allowed_tools:
    - skill
    - read_file
    - bash
    - quickjs
    - context7_resolve-library-id
    - context7_query-docs
    - fetch_fetch
    # - my_mysql_db_all_table_names
    # - my_mysql_db_filter_table_names
    # - my_mysql_db_schema_definitions
    # - my_mysql_db_execute_query
    - ask_user
  max_tool_calls: 100
  show_tool_calls: true

# CLI Settings
cli:
  title: WIMI LLM CLI V4 - Chat with AI
  user_prefix: "user âžœ "
  exit_command: "exit"
  show_system: false

# Database Configuration
database:
  path: "data/app.db"

# System Metadata (supports any key-value pairs, {time} placeholder available)
system_metadata:
  current_time: "{time}"
  current_shell_environment: windows
  # login_user: admin
  # cps_access_token: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJpc3N1c2VyIiwiYXVkIjoiYXVkaWVuY2UiLCJ0ZW5hbnRfaWQiOiIwMDAwMDAiLCJ1c2VyX25hbWUiOiJhZG1pbiIsInJlYWxfbmFtZSI6ImFkbWluIiwidG9rZW5fdHlwZSI6ImFjY2Vzc190b2tlbiIsInJvbGVfbmFtZSI6ImFkbWluaXN0cmF0b3IsLG51bGwiLCJwb3N0X2lkIjoiMTk0MDMxMTQ0NDY1MTc0MTE4NiIsInVzZXJfaWQiOiIxMTIzNTk4ODIxNzM4Njc1MjAxIiwicm9sZV9pZCI6IjExMjM1OTg4MTY3Mzg2NzUyMDEsMjAyNjk2MTk4OTAyNTUyOTg1OCwxOTUxMjI4MDQ4MjA1ODE1ODA5Iiwibmlja19uYW1lIjoiYWRtaW4iLCJkZXRhaWwiOnsidHlwZSI6IndlYiJ9LCJkZXB0X2lkIjoiMTEyMzU5ODgxMzczODY3NTIwMSIsImFjY291bnQiOiJhZG1pbiIsImNsaWVudF9pZCI6InNhYmVyIiwiZXhwIjoxNzc0NzQ0NzIwLCJuYmYiOjE3NzIxNTI3MjB9.6YqYK3-RHCBs8mB8ULqu0Igf_OlNbD_ZD1dHYwEPl4U



server:
  host: ${SERVER_HOST::0.0.0.0}
  port: ${SERVER_PORT::8000}